FROM node:18-bookworm AS build

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .



ENV VITE_API_URL=https://pollifyapp.online:8000
ENV VITE_KEYCLOAK_URL=https://pollifyapp.online:8080

RUN npm run build


# Stage 2: Set up NGINX with Certbot
FROM nginx:1.27-bookworm

# Install Certbot and required packages
RUN apt-get update && apt-get install -y \
    && apt-get clean

COPY --from=build /app/dist /usr/share/nginx/html/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
