FROM node:18-bookworm AS build

WORKDIR /app

COPY ./package.json ./

RUN npm install

COPY . .



ENV VITE_API_URL=http://146.190.165.194:8000
ENV VITE_KEYCLOAK_URL=http://146.190.165.194:8080

RUN npm run build

FROM nginx:1.27-bookworm

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
