import pluginReact from "eslint-plugin-react"
import globals from "globals"
import tseslint from "typescript-eslint"

/** @type {import('eslint').Linter.Config[]} */
export default [
    { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
    { languageOptions: { globals: globals.browser } },
    ...tseslint.configs.recommended,
    pluginReact.configs.flat.recommended,
    pluginReact.configs.flat["jsx-runtime"], // Enable JSX runtime
    { settings: { react: { version: "detect" } } }, // Specify the version of React
    {
        rules: {
            "@typescript-eslint/no-unused-expressions": [
                "error",
                { allowShortCircuit: true, allowTernary: true },
            ],
            "react/react-in-jsx-scope": "off",
        },
    },
    {
        ignores: [
            "**/node_modules/**",
            "**/dist/**",
            "**/build/**",
            "**/out/**",
            "**/.next/**",
            "**/.vercel/**",
            "**/.nuxt/**",
            "**/.cache/**",
            "**/.yarn/**",
            "**/.pnp/**",
            "**/.parcel-cache/**",
            "**/.pnpm-store/**",
            "**/.yarn-store/**",
            "**/.yarn-tmp/**",
            "**/.yarn-integrity/**",
            "**/.yarn-metadata.json",
            "**/.yarnrc.yml",
            "**/.yarnrc.yaml",
            "**/.yarnrc.js",
            "**/.yarnrc",
            "**/.npmrc",
            "**/.npmignore",
            "**/.npmrc.yaml",
            "**/.npmrc.yml",
            "**/.npmrc.js",
            "**/.npmrc",
            "**/.npmignore",
            "**/.npmignore.yaml",
            "**/.npmignore.yml",
            "**/.npmignore.js",
            "**/.npmignore",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.gitkeep",
            "**/.git",
            "**/.hgignore",
            "**/.hg",
            "**/.bzrignore",
            "**/.bzr",
            "**/.DS_Store",
            "**/.gitignore",
            "**/.gitattributes",
            "**/.gitmodules",
            "**/.",
        ],
    },
]
