
services:
  db:
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.prod.db.env
    expose:
      - 5432
  kcdb:
    image: postgres:17.1
    volumes:
      - kcdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}  
      KC_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      FRONTEND_URL: http://localhost    

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kcdb:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080
    depends_on:
      - kcdb


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn polling_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - 80:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  postgres_data:
  static_volume:
  kcdb_data: