
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn polling_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./backend/.prod.env
    depends_on:
      - db
  db:
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.prod.db.env
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: