
services:
  db:
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432
  kcdb:
    image: postgres:17.1
    volumes:
      - kcdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KCDB_NAME}
      POSTGRES_USER: ${KCDB_USER}
      POSTGRES_PASSWORD: ${KCDB_PASSWORD}
    expose:
      - 5432
  keycloak:
    image: ghcr.io/csamuele/polling-app-keycloak:v1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}  
      KC_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      FRONTEND_URL: https://${HOST}
      BACKEND_URL: https://api.${HOST}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kcdb:5432/${KCDB_NAME}
      KC_DB_USERNAME: ${KCDB_USER}
      KC_DB_PASSWORD: ${KCDB_PASSWORD}
      KC_HOSTNAME: https://auth.${HOST}
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_PROXY_PROTOCAL_ENABLED: true
      KC_PROXY_HEADER: xforwarded
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command: 
      - start
      - --import-realm
      - --verbose
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - kcdb


  backend:
    image: ghcr.io/csamuele/polling-app-backend:v1
    command: gunicorn polling_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 127.0.0.1:8000:8000
    environment:
      DEBUG: 0
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      DATABASE: postgres

    depends_on:
      - db
  frontend:
    image: ghcr.io/csamuele/polling-app-frontend:v1
    ports:
      - 3000:3000

volumes:
  postgres_data:
  static_volume:
  kcdb_data: