
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend
    ports:
      - 8000:8000
    env_file:
      - ./.backend.env
    depends_on:
      - db
  db:
    image: postgres:17.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: poll_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  kcdb:
    image: postgres:17.1
    volumes:
      - kcdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      FRONTEND_URL: http://localhost:3000
      BACKEND_URL: http://localhost:8000

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kcdb:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    command: 
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
    depends_on:
      - kcdb
      
      

volumes:
  postgres_data:
  kcdb_data: