name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: polling-app-backend
  IMAGE_NAME_FRONTEND: polling-app-frontend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        id: push-backend
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME_BACKEND }}:latest
      
      - name: Build and push frontend image
        id: push-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME_FRONTEND }}:latest
      
      - name: Generate artifact attestation for backend image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME_BACKEND }}:latest
          subject-digest: ${{ steps.push-backend.outputs.digest }}
          push-to-registry: true
      
      - name: Generate artifact attestation for frontend image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME_FRONTEND }}:latest
          subject-digest: ${{ steps.push-frontend.outputs.digest }}
          push-to-registry: true
      
