name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: polling-app-backend
  IMAGE_NAME_FRONTEND: polling-app-frontend

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        service: [backend, frontend, keycloak]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set image name
        run: echo "IMAGE_NAME=IMAGE_NAME_${{ matrix.service }}" | tr [:lower:] [:upper:] >> $GITHUB_ENV

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        id: build-push
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME }}:v1

      - name: Generate artifact attestation for ${{ matrix.service }} image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner}}/${{ env.IMAGE_NAME }}:v1
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true