name: Publish Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io


jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        service: [backend, frontend, keycloak]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        id: build-push
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner}}/polling-app-${{ matrix.service }}:v1
          build-args: ${{ matrix.service == 'frontend' && 'VITE_API_URL=http://146.190.165.194:8000 VITE_KEYCLOAK_URL=http://146.190.165.194:8080' || '' }}

      - name: Generate artifact attestation for ${{ matrix.service }} image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner}}/polling-app-${{ matrix.service }}
          subject-digest: ${{ steps.build-push.outputs.digest }}
          push-to-registry: true